name: Mirror Kodi Repo to tdbnz-coding (Preserve All Zips, No Workflows)

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Clone mirror repo (tdbnz-coding)
        run: |
          git clone https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/tdbnz-coding/repository.bangvnine-mirror.git mirror

      - name: Delete workflows in mirror if they exist
        run: |
          rm -rf mirror/.github/workflows

      - name: Copy all files except workflows
        run: |
          rsync -a --exclude='.github/workflows' --ignore-existing ./ mirror/
          rsync -a --exclude='.github/workflows' --update ./ mirror/

      - name: Commit and push changes if needed
        working-directory: mirror
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Mirror update on $(date)"
          git push origin main
